### ISSUE TITLE
max_ageの求め方が書いていない

### ISSUE THREAD

**Issue by takanory** [PyDataTokyo/pydata-tokyo-tutorial-1#1]
* max_ageを求めるコードが書いていない
* 多分 `max_age = df['Age'].max()` と思われ

https://github.com/PyDataTokyo/pydata-tokyo-tutorial-1/blob/master/pydatatokyo_tutorial_dh.ipynb

```
# ここにコードがない
print('年齢の最大値: {0}'.format(max_age))

mean_age = df['Age'].mean()
print('年齢の平均値: {0}'.format(mean_age))
```

**Comment by iktakahiro** [comment]
@takanory  Thank you for your report, I've updated the notebook.

see:
https://github.com/PyDataTokyo/pydata-tokyo-tutorial-1/commit/2e50fd9da4b8822b7dc59602fde97fcb3dc42a47#diff-2e11be5cb310baeb9c89b48fc2ff359dR653
